apiVersion: v1
kind: Service
metadata:
  name: blue-service
  labels:
    app: blue
spec:
  selector:
    app: blue
  ports:
    
    - port: 8765
      nodePort: 31000
      targetPort: 9376
  type: LoadBalancer
