apiVersion: v1
kind: Service
metadata:
  name: blue-service
  labels:
    app: blue
spec:
  selector:
      app: blue
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
