name: Build Scan Patch and Push Docker Image

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: sample-app
  IMAGE_TAG: latest

jobs:
  build-scan-patch-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
         context: .
         push: false
         load: true
         tags: sample-app:latest


      - name: Install Trivy
        run: |
          sudo apt-get update
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            gpg --dearmor | \
            sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | \
          sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update

          sudo apt-get install -y trivy

          trivy --version

      - name: Install Copa
        run: |
           git clone https://github.com/project-copacetic/copacetic
           cd copacetic
           make
           # OPTIONAL: install copa to a pathed folder (i.e. /usr/local/bin)
           # Note: if you installed copa via Homebrew, you will need to uninstall it first
           make install

      

      ##- name: Docker Login
       ## uses: docker/login-action@v3
        ##with:
          ##username: ${{ secrets.DOCKER_USERNAME }}
          ##password: ${{ secrets.DOCKER_PASSWORD }}
      # ---------------- Install Vault CLI ----------------
      - name: Install Vault CLI
        run: |
          wget https://releases.hashicorp.com/vault/1.16.2/vault_1.16.2_linux_amd64.zip
          unzip vault_1.16.2_linux_amd64.zip
          sudo mv vault /usr/local/bin/
          vault version

      # ---------------- Fetch Secrets from Vault ----------------
      - name: Get Secrets from Vault
        run: |
          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}

          CREDS=$(vault kv get -format=json secret/dockerhub)

          echo "DOCKER_USERNAME=$(echo $CREDS | jq -r .data.data.username)" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=$(echo $CREDS | jq -r .data.data.password)" >> $GITHUB_ENV

      # ---------------- Docker Login ----------------
      - name: Docker Login
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/sample-app:latest

      
      - name: Scan Image
        run: |
          trivy image \
            --format json \
            -o trivy-report.json \
            $DOCKER_USERNAME/sample-app:latest
      
      - name: Patch Image using Copa
        run: |
          copa patch \
            -i $DOCKER_USERNAME/sample-app:latest \
            -r trivy-report.json \
            -t $DOCKER_USERNAME/sample-app:${{ github.run_number }}

      
      - name: Push Patched Image
        run: |
          docker push $DOCKER_USERNAME/sample-app:${{ github.run_number }}

